### ISSUE TITLE
Introduction and Goals

### ISSUE THREAD

**Issue by srensamblador** [Arquisoft/dechat_es1b#1]

**Comment by LuisBoto** [comment]
Just finished Requierements Overview and Quality Goals, @MarcosCl98 could you do the "Stakeholder" section then?

**Comment by srensamblador** [comment]
I'll do Stakeholders if you don't mind, since I have a bit of time rn

**Comment by srensamblador** [comment]
Initial iteration of 01 section complete, closing issue until refinement is due

**Comment by uo257493** [comment]
Hi, looking at this doc i have seen a little problem relative to stakeholders section. I think this should be reopened to be solved. Greetings

**Comment by uo257493** [comment]
Hi, looking at this doc i have seen a little problem relative to stakeholders section. I think this should be reopened to be solved. Greetings

**Comment by LuisBoto** [comment]
Stakeholders section is complete, now closing issue again
