### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by srensamblador** [Arquisoft/dechat_es1b#10]
## Description
We need a login screen so the user can log in with their POD. 

## Poll
We can either have the log in in its own HTML page or use a pop up window. 
[![](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/HTML%20page)](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/HTML%20page/vote)
[![](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/Pop-up)](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/Pop-up/vote)
[![](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/No%20preference)](https://api.gh-polls.com/poll/01D37VM4MXJ1SVXVZHKHX92XC9/No%20preference/vote)

## Additional notes
I think this task is the most feasible so far and would help us warm up with Angular. There's already a login implementation in the base project that we can use to see the authentication function calls.

**Comment by LuisBoto** [comment]
I would prefer using a pop-up window, however i'm unsure which may be the better/easier solution

**Comment by srensamblador** [comment]
I think both are at the same level of difficulty. A pop-up means we must have a home page though.

**Comment by martinlacorrona** [comment]
O think that it's more easy implement the pop up.

**Comment by MarcosCl98** [comment]
I'm going to modify the style of the log. 👍

**Comment by srensamblador** [comment]
We can close this for now
