### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by srensamblador** [Arquisoft/dechat_es1b#2]

**Comment by martinlacorrona** [comment]
Finished.

**Comment by srensamblador** [comment]
Most POD providers currently have a size quota that will affect how we handle MIME files in our chat, this should be referenced in this section.

**Comment by martinlacorrona** [comment]
Done.

**Comment by martinlacorrona** [comment]
This should have any update?

**Comment by srensamblador** [comment]
> This should have any update?

Maybe not, just reopened all of the doc issues for refining in case a change in one implies changes in others
