### ISSUE TITLE
Development of a basic pod reader

### ISSUE THREAD

**Issue by uo257493** [Arquisoft/dechat_es1b#33]
Create a basic pod reader to start managing its info.

**Comment by martinlacorrona** [comment]
I will to create TextParser to parse messages style.

**Comment by martinlacorrona** [comment]
![asw-podreader](https://user-images.githubusercontent.com/9017738/53802869-3b31f800-3f43-11e9-8d96-814c434b790d.png)
We can use this diagram and start to development this classes.
If @uo257493 agrees we can start to develop.
