### ISSUE TITLE
Public code methods should have documentation

### ISSUE THREAD

**Issue by JavierUrones** [Arquisoft/dechat_es1b#39]
Public methods in javascript should be documentated using jsdoc.

**Comment by srensamblador** [comment]
JSDoc reference here: http://usejsdoc.org/

To generate the HTML:
* Install jsdoc globally (or locally but then you need to provide the route to the bin inside node_modules)
`npm install -g jsdoc`

* Generate HTML for the chosen .js
`jsdoc index.js`

Resulting HTMLs will be stored in the folder out/
