### ISSUE TITLE
Is it possible than an user not have private folder?

### ISSUE THREAD

**Issue by martinlacorrona** [Arquisoft/dechat_es1b#64]

**Comment by LuisBoto** [comment]
I think we should be able to make a check and create the folder no problem, i'll take a look at it

**Comment by srensamblador** [comment]
Maybe we can make our own dechat folder in root?

**Comment by LuisBoto** [comment]
> Maybe we can make our own dechat folder in root?

That may be a better solution. I gotta try creating folders in root and managing folder permissions.

**Comment by srensamblador** [comment]
Fixed by #68
