### ISSUE TITLE
The person who opens chat, messages are displayed and hidden in a loop

### ISSUE THREAD

**Issue by MarcosCl98** [Arquisoft/dechat_es1b#65]

**Comment by martinlacorrona** [comment]
Video: https://www.youtube.com/watch?v=CnSQNrsub9s&feature=youtu.be

**Comment by LuisBoto** [comment]
This is the reason the ui blinks, right?

**Comment by MarcosCl98** [comment]
Yes, but only happen with the person that sent the first message

**Comment by LuisBoto** [comment]
I think i may have a solution to this, i'll try it on a new branch

**Comment by martinlacorrona** [comment]
I close this issue because the UI change.
