### ISSUE TITLE
Architectural decisions

### ISSUE THREAD

**Issue by srensamblador** [Arquisoft/dechat_es1b#8]
Argue the what's and why's of the tech we decide to use

**Comment by srensamblador** [comment]
Since we are ditching Angular we should document that here.
We must explain:
* Why we chose Angular at the beginning
* What made us decide to drop it for Node.js
* What advantages we are expecting from working in Node.js

**Comment by MarcosCl98** [comment]
Ok, i will write it!

**Comment by MarcosCl98** [comment]
Done.

**Comment by srensamblador** [comment]
I'm going through de documentation and this section still has the old Angular content, this we lose the updated version at some point / forgot to push it?
