### ISSUE TITLE
Create Videochat functionality

### ISSUE THREAD

**Issue by LuisBoto** [Arquisoft/dechat_es1b#91]
Users should be able to start a videocall while chatting

**Comment by srensamblador** [comment]
We decided to move personal around, @JavierUrones  will work with @LuisBoto and I'll move into UI. Goal is that everybody works in several aspects of the application

**Comment by LuisBoto** [comment]
I started development on branch features/videochat using the PeerJS library. For now i just made a js file with some basic methods. I ran into some problems with travis since it looks like the nodejs process doesn't like creating webrtc peers tho

**Comment by JavierUrones** [comment]
Established first connection between two friends.

**Comment by srensamblador** [comment]
This is done, closing
