### ISSUE TITLE
Create sending files functionality

### ISSUE THREAD

**Issue by MarcosCl98** [Arquisoft/dechat_es1b#92]
Users should be able to sent files like photos

**Comment by MarcosCl98** [comment]
Send images done.

**Comment by martinlacorrona** [comment]
Should we only allow users to send a whitelist of files? 
Example: .jpg .png
In this case only images.

Do we add also videos and gifs? (This should have his whitelist them)

**Comment by uo257493** [comment]
It will be great conceptually. But considering the storage limitation we have to use a video compressor module or something similar and it will hinder the develop. If you think you may do it easy let's go. But if takes many time maybe another things will have a highter priority

**Comment by martinlacorrona** [comment]
All done.

User now can send images: .jpg, jpeg. .png and .gif.

Also, user can send all of type of files and can be downloaded.
